# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NeT_8Xplj3Zos-msdmQK-yy7XKqd66H5
"""



import streamlit as st
import pandas as pd

# Title
st.title("ASD Screening App")
st.subheader("Based on QCHAT-10 / AQ-10 Score")

# Description
st.markdown("""
This app screens for Autism Spectrum Disorder (ASD) based on QCHAT-10 or AQ-10 questionnaire.
A score of **6 or higher** indicates a **positive ASD screening**.
""")

# Question list for QCHAT-10 or AQ-10 (Yes = 1, No = 0)
questions = [
    "1. Does your child look at you when you call his/her name?",
    "2. How easy is it for you to get eye contact with your child?",
    "3. Does your child point to indicate that s/he wants something?",
    "4. Does your child point to share interest with you?",
    "5. Does your child pretend?",
    "6. Does your child follow where you’re looking?",
    "7. If you or someone else in the family is visibly upset, does your child show signs of wanting to comfort them?",
    "8. Would you describe your child’s first words as typical?",
    "9. Does your child use simple gestures?",
    "10. Does your child stare at nothing with no apparent purpose?"
]

# Collect answers
st.markdown("### Please answer the following questions (Yes = 1, No = 0):")
responses = []
for q in questions:
    responses.append(st.radio(q, [0, 1], horizontal=True))

# Compute score
score = sum(responses)
st.markdown(f"### Total Score: {score}/10")

# Predict ASD
if st.button("Check ASD Risk"):
    if score >= 6:
        st.error("⚠️ High risk of ASD detected. Please consult a professional.")
    else:
        st.success("✅ Low risk of ASD detected.")

# Footer
st.markdown("---")
st.caption("This is a research app and not a diagnostic tool. Please seek professional advice for clinical decisions.")